[package]
edition = "2021"
name = "minimal-versions"
publish = false
version = "0.0.0"

[dependencies]
axum-server-dual-protocol = { path = ".." }
# `tower` v0.4.0 incorrectly only requires `tower-layer` v0.3.0
tower-layer = "0.3.1"
