allow-renamed-params-for = ["..", "core::fmt::Debug"]
allow-unwrap-in-tests = true
allowed-duplicate-crates = [
	"windows-sys",
	"windows-targets",
	"windows_aarch64_gnullvm",
	"windows_aarch64_msvc",
	"windows_i686_gnu",
	"windows_i686_msvc",
	"windows_x86_64_gnu",
	"windows_x86_64_gnullvm",
	"windows_x86_64_msvc",
]
