name: Documentation

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  document-deploy:
    name: Document & Deploy

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Install nightly Rust
        run: |
          rustup toolchain install nightly --profile minimal
          rustup default nightly
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Rustdoc
        env:
          RUSTDOCFLAGS: --crate-version main
        run:
          cargo doc --no-deps --document-private-items -Z rustdoc-map -Z rustdoc-scrape-examples
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Fix permissions
        run: |
          chmod -c -R +rX "target/doc" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: target/doc
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
