name: Lint

on: [push, pull_request]

jobs:
  clippy-rustdoc:
    name: Clippy & Rustdoc

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run Rustdoc
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --examples
