name: Lint

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-rustdoc:
    name: Clippy & Rustdoc

    runs-on: ubuntu-latest

    steps:
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal --component clippy
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run Rustdoc
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --no-deps --document-private-items --lib --examples
