name: Publish

on: [push, pull_request]

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test Publish
        run: cargo publish --dry-run
