name: Publish

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Publish
        run: cargo publish --dry-run
