name: Test

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test:
    name: Build & Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test --all-targets --no-fail-fast
      - name: Documentation Test
        run: cargo test --doc --no-fail-fast

  minimal-versions:
    name: Minimal Versions

    runs-on: ubuntu-latest

    steps:
      - name: Install nightly Rust
        run:
          rustup toolchain install nightly --profile minimal
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        working-directory: minimal-versions
        run: |
          cargo +nightly update -Z minimal-versions
          cargo build
