name: Test

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-test:
    name: Build & Test

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - { version: 1.60.0, msrv: true }
          - { version: stable, msrv: false }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run:
          rustup toolchain install ${{ matrix.rust.version }} --profile minimal
      - name: Build
        run: cargo +${{ matrix.rust.version }} build
      - name: Documentation
        run: cargo +${{ matrix.rust.version }} doc --no-deps
      - name: Test
        if: matrix.rust.msrv == false
        run: cargo +${{ matrix.rust.version }} test --all-targets --no-fail-fast
      - name: Documentation Test
        if: matrix.rust.msrv == false
        run: cargo +${{ matrix.rust.version }} test --doc --no-fail-fast

  minimal-versions:
    name: Minimal Versions

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.60.0
          - stable

    steps:
      - name: Install Rust
        run:
          rustup toolchain install ${{ matrix.rust }} --profile minimal
      - name: Install nightly Rust
        run:
          rustup toolchain install nightly --profile minimal
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        working-directory: minimal-versions
        run: |
          cargo +nightly update -Z minimal-versions
          cargo +${{ matrix.rust }} build
