name: Test

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build & Test

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - { version: 1.66, msrv: true }
          - { version: stable, msrv: false }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup toolchain install ${{ matrix.rust.version }} --profile minimal
          rustup default ${{ matrix.rust.version }}
      - name: Build
        run: cargo build
      - name: Documentation
        run: cargo doc --no-deps
      - name: Test
        if: matrix.rust.msrv == false
        run: cargo test --all-targets --no-fail-fast
      - name: Documentation Test
        if: matrix.rust.msrv == false
        run: cargo test --doc --no-fail-fast

  minimal-versions:
    name: Minimal Versions

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.66
          - stable

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal
          rustup default ${{ matrix.rust }}
      - name: Install nightly Rust
        run: rustup toolchain install nightly --profile minimal
      - name: Build
        working-directory: minimal-versions
        run: |
          cargo +nightly update -Z minimal-versions
          cargo build
