name: Test

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:
    name: Build & Test - ${{ matrix.rust.description }}${{ matrix.features.description }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - { description: MSRV, version: 1.66, msrv: true }
          - { description: Stable, version: stable, msrv: false }
        features:
          - { description: "", features: "" }
          - { description: " (no default features)", features: "--no-default-features" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup toolchain install ${{ matrix.rust.version }} --profile minimal
          rustup default ${{ matrix.rust.version }}
      - name: Fix MSRV dependencies
        if: matrix.rust.msrv == true
        run: cargo update -p tokio --precise 1.38.1
      - name: Build
        run: cargo build ${{ matrix.features.features }}
      - name: Documentation
        run: cargo doc --no-deps ${{ matrix.features.features }}
      - name: Test
        if: matrix.rust.msrv == false
        run: cargo test --all-targets --no-fail-fast ${{ matrix.features.features }}
      - name: Documentation Test
        if: matrix.rust.msrv == false
        run: cargo test --doc --no-fail-fast ${{ matrix.features.features }}

  minimal-versions:
    name: Minimal Versions - ${{ matrix.rust.description }}${{ matrix.features.description }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - { description: MSRV, version: 1.66 }
          - { description: Stable, version: stable }
        features:
          - { description: "", features: "" }
          - { description: " (no default features)", features: "--no-default-features" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust
        run: |
          rustup toolchain install ${{ matrix.rust.version }} --profile minimal
          rustup default ${{ matrix.rust.version }}
      - name: Install nightly Rust
        run: rustup toolchain install nightly --profile minimal
      - name: Build
        working-directory: minimal-versions
        run: |
          cargo +nightly update -Z minimal-versions
          cargo build ${{ matrix.features.features }}
